require("vt")
-- require('todo-comments').setup {
--   keywords = {
--     FIX = {
--       icon = " ", -- icon used for the sign, and in search results
--       color = "error", -- can be a hex color, or a named color (see below)
--       alt = { "FIXME", "BUG", "FIXIT", "ISSUE" }, -- a set of other keywords that all map to this FIX keywords
--       -- signs = false, -- configure signs for some keywords individually
--     },
--     TODO = { icon = " ", color = "info" },
--     HACK = { icon = " ", color = "warning" },
--   },
--   gui_style = {
--     fg = "NONE",
--     bg = "BOLD",
--   },
--   colors = {
--     error = { "DiagnosticError", "ErrorMsg", "#DC2626" },
--     warning = { "DiagnosticWarn", "WarningMsg", "#FBBF24" },
--     info = { "DiagnosticInfo", "#2563EB" },
--     hint = { "DiagnosticHint", "#10B981" },
--     default = { "Identifier", "#7C3AED" },
--     test = { "Identifier", "#FF00FF" }
--   },
--   search = {
--     command = "rg",
--     args = {
--       "--color=never",
--       "--no-heading",
--       "--with-filename",
--       "--line-number",
--       "--column",
--     },
--   },
-- }

